import "./globals.css";
import type { Metadata } from "next";
import React from 'react';

export const metadata: Metadata = {
  title: "Ali Shahid | Web Dev",
  description: "Generated by create next app",
};

import { Inter } from 'next/font/google'

const inter = Inter({ 
  subsets: ['latin'],
  display: 'swap'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  )
}

export const dynamic = 'force-static'
export const revalidate = 86400